// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	AddToBlacklist(ctx context.Context, arg AddToBlacklistParams) error
	BlacklistAccessToken(ctx context.Context, arg BlacklistAccessTokenParams) error
	BlacklistRefreshToken(ctx context.Context, arg BlacklistRefreshTokenParams) error
	CleanupExpiredTokens(ctx context.Context) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error)
	IsTokenBlacklisted(ctx context.Context, jti string) (int64, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
