// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reviews.sql

package database

import (
	"context"
	"time"
)

const countReviewsBySpot = `-- name: CountReviewsBySpot :one
SELECT COUNT(*) FROM reviews 
WHERE spot_id = ?
`

func (q *Queries) CountReviewsBySpot(ctx context.Context, spotID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsBySpot, spotID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByUser = `-- name: CountReviewsByUser :one
SELECT COUNT(*) FROM reviews 
WHERE user_id = ?
`

func (q *Queries) CountReviewsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :exec
INSERT INTO reviews (
    id, spot_id, user_id, rating, comment
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreateReviewParams struct {
	ID      string `json:"id"`
	SpotID  string `json:"spot_id"`
	UserID  string `json:"user_id"`
	Rating  int32  `json:"rating"`
	Comment string `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) error {
	_, err := q.db.ExecContext(ctx, createReview,
		arg.ID,
		arg.SpotID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	return err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews 
WHERE id = ?
`

func (q *Queries) DeleteReview(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReview, id)
	return err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT * FROM reviews 
WHERE id = ?
`

func (q *Queries) GetReviewByID(ctx context.Context, id string) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByID, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.SpotID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByUserAndSpot = `-- name: GetReviewByUserAndSpot :one
SELECT * FROM reviews 
WHERE user_id = ? AND spot_id = ?
`

type GetReviewByUserAndSpotParams struct {
	UserID string `json:"user_id"`
	SpotID string `json:"spot_id"`
}

func (q *Queries) GetReviewByUserAndSpot(ctx context.Context, arg GetReviewByUserAndSpotParams) (Review, error) {
	row := q.db.QueryRowContext(ctx, getReviewByUserAndSpot, arg.UserID, arg.SpotID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.SpotID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpotRatingStats = `-- name: GetSpotRatingStats :one
SELECT 
    AVG(rating) as average_rating,
    COUNT(*) as review_count
FROM reviews 
WHERE spot_id = ?
`

type GetSpotRatingStatsRow struct {
	AverageRating float64 `json:"average_rating"`
	ReviewCount   int64   `json:"review_count"`
}

func (q *Queries) GetSpotRatingStats(ctx context.Context, spotID string) (GetSpotRatingStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSpotRatingStats, spotID)
	var i GetSpotRatingStatsRow
	err := row.Scan(&i.AverageRating, &i.ReviewCount)
	return i, err
}

const listReviewsBySpot = `-- name: ListReviewsBySpot :many
SELECT
  r.id,
  r.spot_id,
  r.user_id,
  r.rating,
  r.comment,
  r.created_at,
  r.updated_at,
  u.name          AS user_name
FROM reviews r
JOIN users u ON r.user_id = u.id
WHERE r.spot_id = ?
ORDER BY r.created_at DESC
LIMIT ? OFFSET ?
`

type ListReviewsBySpotParams struct {
	SpotID string `json:"spot_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListReviewsBySpotRow struct {
	ID        string    `json:"id"`
	SpotID    string    `json:"spot_id"`
	UserID    string    `json:"user_id"`
	Rating    int32     `json:"rating"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserName  string    `json:"user_name"`
}

func (q *Queries) ListReviewsBySpot(ctx context.Context, arg ListReviewsBySpotParams) ([]ListReviewsBySpotRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsBySpot, arg.SpotID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsBySpotRow
	for rows.Next() {
		var i ListReviewsBySpotRow
		if err := rows.Scan(
			&i.ID,
			&i.SpotID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT r.*, s.name as spot_name, s.category as spot_category
FROM reviews r
JOIN spots s ON r.spot_id = s.id
WHERE r.user_id = ?
ORDER BY r.created_at DESC
LIMIT ? OFFSET ?
`

type ListReviewsByUserParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListReviewsByUserRow struct {
	ID           string    `json:"id"`
	SpotID       string    `json:"spot_id"`
	UserID       string    `json:"user_id"`
	Rating       int32     `json:"rating"`
	Comment      string    `json:"comment"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	SpotName     string    `json:"spot_name"`
	SpotCategory string    `json:"spot_category"`
}

func (q *Queries) ListReviewsByUser(ctx context.Context, arg ListReviewsByUserParams) ([]ListReviewsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsByUserRow
	for rows.Next() {
		var i ListReviewsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.SpotID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SpotName,
			&i.SpotCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :exec
UPDATE reviews 
SET rating = ?, comment = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateReviewParams struct {
	Rating  int32  `json:"rating"`
	Comment string `json:"comment"`
	ID      string `json:"id"`
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) error {
	_, err := q.db.ExecContext(ctx, updateReview, arg.Rating, arg.Comment, arg.ID)
	return err
}