// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: spots.sql

package database

import (
	"context"
	"time"
)

const countSpots = `-- name: CountSpots :one
SELECT COUNT(*) FROM spots 
WHERE (? = '' OR name LIKE ?)
  AND (? = '' OR category = ?)
  AND (? = '' OR country_code = ?)
`

type CountSpotsParams struct {
	Column1     interface{} `json:"column_1"`
	Name        string      `json:"name"`
	Column3     interface{} `json:"column_3"`
	Category    string      `json:"category"`
	Column5     interface{} `json:"column_5"`
	CountryCode string      `json:"country_code"`
}

func (q *Queries) CountSpots(ctx context.Context, arg CountSpotsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpots,
		arg.Column1,
		arg.Name,
		arg.Column3,
		arg.Category,
		arg.Column5,
		arg.CountryCode,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpotsByCategory = `-- name: CountSpotsByCategory :one
SELECT COUNT(*) FROM spots 
WHERE category = ?
`

func (q *Queries) CountSpotsByCategory(ctx context.Context, category string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpotsByCategory, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSpotsByCountry = `-- name: CountSpotsByCountry :one
SELECT COUNT(*) FROM spots 
WHERE country_code = ?
`

func (q *Queries) CountSpotsByCountry(ctx context.Context, countryCode string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSpotsByCountry, countryCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpot = `-- name: CreateSpot :exec
INSERT INTO spots (
    id, name, category, address, country_code
) VALUES (
    ?, ?, ?, ?, ?
)
`

type CreateSpotParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Category    string `json:"category"`
	Address     string `json:"address"`
	CountryCode string `json:"country_code"`
}

func (q *Queries) CreateSpot(ctx context.Context, arg CreateSpotParams) error {
	_, err := q.db.ExecContext(ctx, createSpot,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Address,
		arg.CountryCode,
	)
	return err
}

const deleteSpot = `-- name: DeleteSpot :exec
DELETE FROM spots 
WHERE id = ?
`

func (q *Queries) DeleteSpot(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSpot, id)
	return err
}

const getSpotByID = `-- name: GetSpotByID :one
SELECT id, name, category, address, country_code, created_at, updated_at FROM spots 
WHERE id = ?
`

type GetSpotByIDRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	Address     string    `json:"address"`
	CountryCode string    `json:"country_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetSpotByID(ctx context.Context, id string) (GetSpotByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSpotByID, id)
	var i GetSpotByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Address,
		&i.CountryCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpots = `-- name: ListSpots :many
SELECT id, name, category, address, country_code, created_at, updated_at FROM spots 
WHERE (? = '' OR name LIKE ?)
  AND (? = '' OR category = ?)
  AND (? = '' OR country_code = ?)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSpotsParams struct {
	Column1     interface{} `json:"column_1"`
	Name        string      `json:"name"`
	Column3     interface{} `json:"column_3"`
	Category    string      `json:"category"`
	Column5     interface{} `json:"column_5"`
	CountryCode string      `json:"country_code"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type ListSpotsRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	Address     string    `json:"address"`
	CountryCode string    `json:"country_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListSpots(ctx context.Context, arg ListSpotsParams) ([]ListSpotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpots,
		arg.Column1,
		arg.Name,
		arg.Column3,
		arg.Category,
		arg.Column5,
		arg.CountryCode,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpotsRow
	for rows.Next() {
		var i ListSpotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Address,
			&i.CountryCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpotsByCategory = `-- name: ListSpotsByCategory :many
SELECT id, name, category, address, country_code, created_at, updated_at FROM spots 
WHERE category = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSpotsByCategoryParams struct {
	Category string `json:"category"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

type ListSpotsByCategoryRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	Address     string    `json:"address"`
	CountryCode string    `json:"country_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListSpotsByCategory(ctx context.Context, arg ListSpotsByCategoryParams) ([]ListSpotsByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpotsByCategory, arg.Category, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpotsByCategoryRow
	for rows.Next() {
		var i ListSpotsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Address,
			&i.CountryCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpotsByCountry = `-- name: ListSpotsByCountry :many
SELECT id, name, category, address, country_code, created_at, updated_at FROM spots 
WHERE country_code = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSpotsByCountryParams struct {
	CountryCode string `json:"country_code"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

type ListSpotsByCountryRow struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Category    string    `json:"category"`
	Address     string    `json:"address"`
	CountryCode string    `json:"country_code"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) ListSpotsByCountry(ctx context.Context, arg ListSpotsByCountryParams) ([]ListSpotsByCountryRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpotsByCountry, arg.CountryCode, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpotsByCountryRow
	for rows.Next() {
		var i ListSpotsByCountryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Address,
			&i.CountryCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpot = `-- name: UpdateSpot :exec
UPDATE spots 
SET name = ?, category = ?, 
    address = ?, country_code = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateSpotParams struct {
	Name        string `json:"name"`
	Category    string `json:"category"`
	Address     string `json:"address"`
	CountryCode string `json:"country_code"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateSpot(ctx context.Context, arg UpdateSpotParams) error {
	_, err := q.db.ExecContext(ctx, updateSpot,
		arg.Name,
		arg.Category,
		arg.Address,
		arg.CountryCode,
		arg.ID,
	)
	return err
}