---
services:
  mysql:
    image: mysql:8.0
    container_name: bocchi-the-map-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-change_me_in_production}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-bocchi_the_map}
      MYSQL_USER: ${MYSQL_USER:-bocchi_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-change_me_too}
    ports:
      - "3306:3306"
    # Volume configuration moved to environment-specific override files:
    # For test: docker-compose up (uses docker-compose.override.yml with tmpfs)
    # For production: docker-compose -f docker-compose.yml \\
    #   -f docker-compose.prod.yml up (uses persistent volume)
    command: --default-authentication-plugin=mysql_native_password

# Volume definitions moved to environment-specific override files
